name: Run all tests
on: [push]

jobs:
  testRunnerInAllModes:
    name: Test play and edit mode
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: Unity.Mathematics.FixedPoint

      # Checkout repository (required to test local actions)
      - name: Checkout test project
        uses: actions/checkout@v2
        with:
          repository: danielmansson/Unity.Mathematics.FixedPoint.TestProject
          path: test-project

      # Configure test runner
      - name: Run tests
        id: testRunner
        uses: webbertakken/unity-test-runner@v1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_PROJECT_PATH: test-project
          TEST_MODE: all

      # Upload artifacts
      - name: Expose as artifact
        uses: actions/upload-artifact@v1
        with:
          name: Test results (all modes)
          path: ${{ steps.testRunner.outputs.artifactsPath }}

